# Generated by Django 4.1.2 on 2022-11-22 05:30

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StaffAccount",
            fields=[
                ("accountID", models.AutoField(primary_key=True, serialize=False)),
                ("firstName", models.CharField(max_length=100)),
                ("lastName", models.CharField(max_length=100)),
                (
                    "dob",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2022, 11, 22, 5, 30, 0, 656341, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("email", models.EmailField(max_length=100)),
                ("passwd", models.CharField(max_length=50)),
                (
                    "personalContactNo",
                    models.BigIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1000000000),
                            django.core.validators.MaxValueValidator(9999999999),
                        ]
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=7
                    ),
                ),
                ("staffID", models.IntegerField()),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="StudentAccount",
            fields=[
                ("accountID", models.AutoField(primary_key=True, serialize=False)),
                ("firstName", models.CharField(max_length=100)),
                ("lastName", models.CharField(max_length=100)),
                (
                    "dob",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2022, 11, 22, 5, 30, 0, 656341, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("email", models.EmailField(max_length=100)),
                ("passwd", models.CharField(max_length=50)),
                (
                    "personalContactNo",
                    models.BigIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1000000000),
                            django.core.validators.MaxValueValidator(9999999999),
                        ]
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=7
                    ),
                ),
                ("rollNo", models.BigIntegerField()),
                (
                    "branch",
                    models.CharField(
                        choices=[("BE", "BE"), ("BTECH", "BTECH")], max_length=10
                    ),
                ),
                (
                    "parentContactNo",
                    models.BigIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1000000000),
                            django.core.validators.MaxValueValidator(9999999999),
                        ]
                    ),
                ),
                ("currentRoomBooked", models.CharField(default="0", max_length=10)),
                ("CGPA", models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={"abstract": False,},
        ),
    ]
