# Generated by Django 4.1.2 on 2022-11-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0002_remove_staffaccount_dob_remove_studentaccount_dob"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hostel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("numberOfRooms", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roomNumber", models.PositiveIntegerField()),
                ("hostelName", models.CharField(max_length=50)),
                ("occupancy", models.BinaryField()),
                ("availableSeats", models.PositiveIntegerField()),
                (
                    "roomType",
                    models.CharField(
                        choices=[("AC", "AC"), ("NONAC", "NONAC")], max_length=10
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sessions",
            fields=[
                ("sessionID", models.AutoField(primary_key=True, serialize=False)),
                ("startTime", models.DateTimeField()),
                ("endTime", models.DateTimeField()),
                ("minCGPA", models.DecimalField(decimal_places=2, max_digits=4)),
                ("maxCGPA", models.DecimalField(decimal_places=2, max_digits=4)),
                ("baseRate", models.DecimalField(decimal_places=2, max_digits=8)),
                ("costWithAC", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
