# Generated by Django 4.1.2 on 2022-11-24 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0007_alter_room_occupancy"),
    ]

    operations = [
        migrations.RemoveField(model_name="room", name="occupancy",),
    ]
