# Generated by Django 4.1.2 on 2022-11-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0008_remove_room_occupancy"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="occupancy",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
