# Generated by Django 4.1.2 on 2022-11-24 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0011_alter_room_blocktimeend"),
    ]

    operations = [
        migrations.RemoveField(model_name="room", name="blockTimeEnd",),
    ]
