# Generated by Django 4.1.2 on 2022-11-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0013_room_blocktimeend"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostel",
            name="forGender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], default="M", max_length=7
            ),
        ),
    ]
