# Generated by Django 4.1.2 on 2022-11-24 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0014_hostel_forgender"),
    ]

    operations = [
        migrations.RemoveField(model_name="room", name="isBlocked",),
    ]
