# Generated by Django 4.1.2 on 2022-11-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0017_remove_room_isblocked"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="isBlocked",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
