# Generated by Django 4.1.2 on 2022-11-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0018_room_isblocked"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cardNumber", models.BigIntegerField()),
                ("expiryMonth", models.PositiveIntegerField()),
                ("expiryYear", models.PositiveIntegerField()),
                ("cardHolderName", models.CharField(max_length=200)),
                ("securityCode", models.PositiveIntegerField()),
                ("hostelName", models.CharField(max_length=10)),
                ("roomNumber", models.PositiveIntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
