# Generated by Django 4.1.2 on 2022-11-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0021_alter_studentaccount_cgpa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffaccount",
            name="email",
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="staffaccount",
            name="staffID",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="studentaccount",
            name="email",
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="studentaccount",
            name="rollNo",
            field=models.BigIntegerField(unique=True),
        ),
    ]
