# Generated by Django 4.1.2 on 2022-11-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="staffaccounts", name="age",),
        migrations.RemoveField(model_name="studentaccounts", name="age",),
        migrations.AddField(
            model_name="staffaccounts",
            name="dob",
            field=models.DateField(default="1997-10-19"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentaccounts",
            name="dob",
            field=models.DateField(default=1997),
            preserve_default=False,
        ),
    ]
