# Generated by Django 4.1.2 on 2022-11-18 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0003_remove_staffaccounts_dob_remove_studentaccounts_dob"),
    ]

    operations = [
        migrations.DeleteModel(name="StaffAccounts",),
        migrations.DeleteModel(name="StudentAccounts",),
    ]
