# Generated by Django 4.1.2 on 2022-11-18 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("login", "0004_delete_staffaccounts_delete_studentaccounts"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffAccounts",
            fields=[
                ("accountID", models.IntegerField(primary_key=True, serialize=False)),
                ("firstName", models.CharField(max_length=100)),
                ("lastName", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("passwd", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Genders", "Male Female")], max_length=7
                    ),
                ),
                ("staffID", models.IntegerField()),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="StudentAccounts",
            fields=[
                ("accountID", models.IntegerField(primary_key=True, serialize=False)),
                ("firstName", models.CharField(max_length=100)),
                ("lastName", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("passwd", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Genders", "Male Female")], max_length=7
                    ),
                ),
                ("rollNo", models.IntegerField()),
                (
                    "branch",
                    models.CharField(choices=[("Branches", "BE BTECH")], max_length=10),
                ),
                (
                    "parentContactNo",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(9999999999)
                        ]
                    ),
                ),
                ("currentRoomBooked", models.CharField(max_length=10)),
                ("CGPA", models.DecimalField(decimal_places=2, max_digits=2)),
            ],
            options={"abstract": False,},
        ),
    ]
