# Generated by Django 4.1.2 on 2022-11-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0005_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="StaffAccounts",),
        migrations.DeleteModel(name="StudentAccounts",),
    ]
